# Generated by Django 5.1.3 on 2024-11-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_paciente',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
